---
# tasks file for vim
- name: update Cache on debian.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: install required packages.
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  become: yes
  tags:
    - install_packages

- name: ensure .vim/{autoload,bundle} directory exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"

- name: ensure Ppthogen is in place.
  ansible.builtin.get_url:
    dest: "{{ vim_dir }}/autoload/pathogen.vim"
    url: https://tpo.pe/pathogen.vim

- name: deploy plugins.
  ansible.builtin.git:
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop: "{{ plugins }}"

- name: ensure .vimrc config in place.
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ vimrc }}"
    backup: yes
    mode: 0640
