---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Verify Vim is installed
      ansible.builtin.command: |
        vim --version
      register: vim_version
      tags: verify

    - name: Verify Vim version
      ansible.builtin.debug:
        var: vim_version.stdout_lines
      tags: verify
